# Generated by Django 5.2.3 on 2025-06-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.circuito'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.circuito'),
        ),
        migrations.AddField(
            model_name='penalizacao',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.circuito'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.circuito'),
        ),
    ]
