# Generated by Django 5.2.3 on 2025-06-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_circuito_alter_pontuacao_valor_atividade_circuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='rank.circuito'),
        ),
    ]
