# Generated by Django 5.2.3 on 2025-06-27 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='circuito',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='circuito',
            name='data_encerramento',
        ),
        migrations.RemoveField(
            model_name='circuito',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='circuito',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='pontuacao_fixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circuito',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuito',
            name='tipo',
            field=models.CharField(choices=[('prova', 'Prova'), ('brincadeira', 'Brincadeira')], default='prova', max_length=20),
        ),
        migrations.AddField(
            model_name='circuito',
            name='valor_padrao',
            field=models.IntegerField(default=0, help_text='Usado se a pontuação for fixa'),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
