# Generated by Django 5.2.3 on 2025-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_remove_pontuacao_atividade_remove_circuito_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
