# Generated by Django 5.2.3 on 2025-06-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_circuito_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='cor',
        ),
        migrations.AddField(
            model_name='equipe',
            name='brasao',
            field=models.ImageField(blank=True, null=True, upload_to='brasoes/'),
        ),
    ]
