# Generated by Django 5.2.3 on 2025-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0008_remove_equipe_cor_equipe_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='brasao',
            field=models.ImageField(blank=True, null=True, upload_to='media/brasoes/'),
        ),
    ]
