# Generated by Django 5.2.3 on 2025-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0009_alter_equipe_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='brasao',
            field=models.ImageField(blank=True, null=True, upload_to='brasoes/'),
        ),
    ]
