# Generated by Django 5.2.3 on 2025-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0011_penalizacao_usuario_pontuacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='modo_ranking',
            field=models.CharField(choices=[('pontuacao', 'Por Pontuação'), ('tempo', 'Por Tempo (quanto menor, melhor)')], default='pontuacao', help_text='Define como o ranking será ordenado: por pontos ou por tempo', max_length=20),
        ),
    ]
