# Generated by Django 5.2.3 on 2025-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0012_circuito_modo_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='tempo_em_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
