# Generated by Django 5.2.3 on 2025-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0013_pontuacao_tempo_em_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='tempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
