# Generated by Django 5.2.3 on 2025-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0015_penalizacao_aprovado_por_penalizacao_data_aprovacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='tempo_em_minutos',
        ),
        migrations.AddField(
            model_name='equipe',
            name='tempo_em_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
