# Generated by Django 5.2.3 on 2025-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0016_remove_pontuacao_tempo_em_minutos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='tempo_total',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='tempo_em_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
