# Generated by Django 5.2.3 on 2025-07-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0017_remove_equipe_tempo_total_pontuacao_tempo_em_minutos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='tempo_em_minutos',
            new_name='tempo_em_segundos',
        ),
        migrations.RenameField(
            model_name='pontuacao',
            old_name='tempo_em_minutos',
            new_name='tempo_em_segundos',
        ),
    ]
