# Generated by Django 5.2.3 on 2025-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0019_penalizacao_tempo_em_segundos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
